[package]
name = "puzzles"
version = "0.1.0"
authors = ["toshiki goto <gotoshi.euphonium@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"

[profile.dev]
opt-level = 0
debug = true
